//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Магазин_техники
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Техника
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Техника()
        {
            this.T_Действия_на_складе = new HashSet<T_Действия_на_складе>();
            this.Товары_договора = new HashSet<Товары_договора>();
        }
    
        public int id { get; set; }
        public string тип_техники { get; set; }
        public string модель { get; set; }
        public string производитель { get; set; }
        public string фото { get; set; }
        public int цена { get; set; }
    
        public virtual T_Вид_техники T_Вид_техники { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Действия_на_складе> T_Действия_на_складе { get; set; }
        public virtual T_Производитель T_Производитель { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Товары_договора> Товары_договора { get; set; }
    }
}
